version: '3.7'

services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        platform: linux/x86_64
        ports:
            - "3003:3001"
        environment:
            - HOST=${HOST}
            - PORT=${PORT}
            - TOKEN_SECRET=${TOKEN_SECRET}
            - FRONTEND_URL=${FRONTEND_URL}
            - DATABASE_URL=${DATABASE_URL}
            - GMAIL_EMAIL=${GMAIL_EMAIL}
            - GMAIL_PASSWORD=${GMAIL_PASSWORD}
            - LOGO_URL=${LOGO_URL}
        networks:
            - isco_network
        restart: unless-stopped
        command: sh -c "npm rebuild sqlite3 && npm run dev"

    frontend:
        build:
            context: ../frontend_job_board_system/.
            dockerfile: Dockerfile
            args:
                NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        platform: linux/x86_64
        ports:
            - "3002:3000"
        depends_on:
            - backend
        environment:
            - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
            - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
            - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
            - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
            - API_URL=${API_URL}
        networks:
            - isco_network
        restart: unless-stopped

networks:
    isco_network:
